name: Docker Image CI
on:
  push:
    branches: [ "ci-cd-test" ]
  pull_request:
    branches: [ "ci-cd-test" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: echo "Hello from Ci & CD startup program"
    - name: Listing Dir
      run: ls
    - name: Check Vars
      run: ${{ toJson(vars) }}
      
