name: Detect Changed Services

on:
  push:
    branches: [ "ED-29" ]  # Runs only when commits are pushed to 'dev'
  workflow_dispatch:    # Allow manual trigger

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Check if .NET 8 is installed, install if missing
      - name: Install .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install NUKE
        run: |
          dotnet tool install Nuke.GlobalTool --global
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: NUKE version
        run: nuke --version

      - name: Print Changed Services
        run: nuke PrintChangedServices

